# Generated by Django 2.2.6 on 2019-11-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Genre Title')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Article Title')),
                ('description', models.TextField(verbose_name='Article Short Description')),
                ('image', models.CharField(max_length=1000, verbose_name='Cover Image URL')),
                ('created_at', models.DateTimeField(verbose_name='Publication Date')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Genre')),
            ],
        ),
    ]
