# Generated by Django 2.2.6 on 2019-11-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('image', models.CharField(max_length=1000, verbose_name='Avatar URL')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Film Duration'),
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.TextField(default=None, null=True, verbose_name='Film URL'),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Production year'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='films.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Director'),
        ),
    ]
