# Generated by Django 2.2.6 on 2019-11-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20191104_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(null=True, to='films.Actor'),
        ),
    ]
