# Generated by Django 2.2.6 on 2019-11-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20191104_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
    ]
