# Generated by Django 2.2.6 on 2019-11-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_rate_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Seance time')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Secret Code')),
                ('seat_number', models.IntegerField(default=0, verbose_name='Seat number')),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.Seance')),
            ],
        ),
    ]
