# Generated by Django 2.2.6 on 2019-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_book_seance'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='price',
            field=models.IntegerField(default=1500, verbose_name='Price'),
        ),
    ]
